baseURL = "https://kat.education"
defaultContentLanguage = "de"
languageCode = "de"
title = "KEDU"
theme = "kedu-theme"
publishDir = "docs"

[params]
	imgurClientId = "c49ece7d26d301d"

[markup]
  	defaultMarkdownHandler = "goldmark"
  	[markup.goldmark]
    	[markup.goldmark.renderer]
      		unsafe = true

[menu]

	[[menu.main]]
	    identifier = "home"
	    name = "Verein"
	    title = "home section"
	    url = "/"
	    weight = 1

	[[menu.footer]]
	    identifier = "legal"
	    name = "Satzung"
	    title = "Satzung"
	    url = "/Satzung_10012020.pdf"
	    weight = 2

